include ../common.mak

all:

install:
	install -d $(INSTALLDIR)/sbin
	install -d $(INSTALLDIR)/usr/sbin
	install -d $(INSTALLDIR)/lib
	install -d $(INSTALLDIR)/etc/init.d/

	tar -xvf unum.tgz -C $(INSTALLDIR)/
clean:
